[package]
name = "pathfinder-wotr-editor"
version = "0.1.0"
authors = ["Francois"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# When updating this git ref, please rebuild azul-dll from source and generally speaking
# follow instructions on the azul github repo.
# Be prepared for a long-ish battle (1~2 hours) of following non-existing instructions.
azul = { git = "https://github.com/maps4print/azul", rev = "548a7990b587e3fa98d126ec7bd46ca4a2fcf168" }
