[package]
name = "pathfinder-wotr-editor"
version = "0.1.0"
authors = ["Francois"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.1", features = ["tokio"] }
iced_native = { version = "0.2", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tinyfiledialogs = "3.3"
tokio = { version = "0.2", features = ["blocking", "fs"] }
dirs = "3.0"
async-trait = "0.1"
futures = "0.3"
zip = "0.5"
async-channel = "1.1"
log = "0.4"
env_logger = "0.7"
